import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const inputPath = resolve(root, 'docs/classList.md')
const outputPath = resolve(root, 'src/data/courses.js')

const SUBJECT_ALIASES = {
  Mathematics: ['Math'],
  English: ['English'],
  Science: ['Science'],
  'Phys. Ed.': ['Physical Education'],
  'Practical Arts': ['Practical Arts', 'Pratical Arts'],
  'Social Studies': ['Social Studies'],
  Arts: [
    'Visual and Performing Arts',
    'Visual and Preforming Arts',
    'Visual and Perfoming Arts',
    'Visual and Preforming',
  ],
  Languages: ['Foreign Language'],
  Support: ['Student Support Classes'],
}

const QUALIFIER_NOISE = new Set(['Application or Audition Only'])

const aliasToCanonical = new Map()
for (const [canonical, aliases] of Object.entries(SUBJECT_ALIASES)) {
  for (const alias of aliases) aliasToCanonical.set(alias.toLowerCase(), canonical)
}

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function parseRow(line) {
  const parts = line.split('|').map((c) => c.trim())
  if (parts.length < 7) return null
  const [, name, subjectRaw, prereq, suggestedReqs, teachers, desc] = parts
  if (!name || name === 'Class' || name.startsWith('---')) return null

  const categories = []
  const qualifiers = []
  for (const piece of subjectRaw.split(',').map((p) => p.trim()).filter(Boolean)) {
    if (QUALIFIER_NOISE.has(piece)) {
      qualifiers.push(piece)
      continue
    }
    const canonical = aliasToCanonical.get(piece.toLowerCase())
    if (canonical) {
      if (!categories.includes(canonical)) categories.push(canonical)
    } else {
      qualifiers.push(piece)
    }
  }

  return {
    id: slugify(name),
    name,
    categories,
    qualifiers,
    prereq: prereq && prereq.toLowerCase() !== 'none' ? prereq : '',
    suggestedReqs: suggestedReqs && suggestedReqs.toLowerCase() !== 'none' ? suggestedReqs : '',
    teachers,
    description: desc,
  }
}

const md = readFileSync(inputPath, 'utf8')
const courses = md
  .split(/\r?\n/)
  .map(parseRow)
  .filter(Boolean)

const unrecognized = new Set()
for (const line of md.split(/\r?\n/)) {
  const parts = line.split('|').map((c) => c.trim())
  if (parts.length < 7) continue
  const subjectRaw = parts[2]
  if (!subjectRaw || subjectRaw === 'Subject' || subjectRaw.startsWith('---')) continue
  for (const piece of subjectRaw.split(',').map((p) => p.trim()).filter(Boolean)) {
    if (QUALIFIER_NOISE.has(piece)) continue
    if (!aliasToCanonical.has(piece.toLowerCase())) unrecognized.add(piece)
  }
}
if (unrecognized.size) {
  console.warn('[build-courses] unrecognized subjects:', [...unrecognized])
}

mkdirSync(dirname(outputPath), { recursive: true })
const banner = `// AUTO-GENERATED by scripts/build-courses.mjs from docs/classList.md\n// Do not edit by hand. Run \`node scripts/build-courses.mjs\` to regenerate.\n\n`
const body = `export const COURSES = ${JSON.stringify(courses, null, 2)}\n\nexport const CATEGORY_LABELS = ${JSON.stringify(Object.keys(SUBJECT_ALIASES), null, 2)}\n`
writeFileSync(outputPath, banner + body)
console.log(`[build-courses] wrote ${courses.length} courses to ${outputPath}`)
